-- Layer 4: Simulation & Scenario Engine Database Schema

-- Scenarios are immutable configurations that can be reused across runs
CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scenario_hash TEXT UNIQUE NOT NULL, -- SHA-256 of canonical JSON
    scenario_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sim_scenarios_hash ON simulation_scenarios(scenario_hash);

-- Runs represent a single execution of the Simulation Engine
CREATE TABLE IF NOT EXISTS simulation_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season INT NOT NULL,
    event_slug TEXT NOT NULL,
    session_slug TEXT NOT NULL,
    driver_code TEXT NOT NULL,
    
    scenario_hash TEXT NOT NULL REFERENCES simulation_scenarios(scenario_hash),
    
    status TEXT NOT NULL CHECK (status IN ('started', 'success', 'failed')),
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    results_summary JSONB, -- Stores high-level summary (e.g., total_time, warnings)
    error_message TEXT
);
CREATE INDEX IF NOT EXISTS idx_sim_runs_lookup ON simulation_runs(season, event_slug, session_slug, driver_code);

-- Assets generated by the run (e.g., full lap-by-lap results in Parquet)
CREATE TABLE IF NOT EXISTS simulation_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    simulation_run_id UUID NOT NULL REFERENCES simulation_runs(id) ON DELETE CASCADE,
    asset_type TEXT NOT NULL, -- e.g., 'deterministic_race', 'monte_carlo_results'
    storage_path TEXT NOT NULL, -- Path to parquet/json on filesystem
    file_format TEXT NOT NULL, -- 'parquet', 'json'
    checksum TEXT NOT NULL, -- SHA-256
    row_count INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sim_assets_run ON simulation_assets(simulation_run_id);
